package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/tools/go/packages"
)

const marker = "//generate:reset"

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "%v\n", err)
	}
}

func run() error {
	root, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("getwd: %w", err)
	}

	fset := token.NewFileSet()
	pkgs, err := parseDirRecursive(fset, root)
	if err != nil {
		return fmt.Errorf("parse: %w", err)
	}

	for dir, pkg := range pkgs {
		structs := findMarkedStructs(pkg)
		if len(structs) == 0 {
			continue
		}

		code, err := generateFile(pkg.Name, structs)
		if err != nil {
			return fmt.Errorf("generate %s: %w", dir, err)
		}

		outPath := filepath.Join(pkg.GoFiles[0][:len(pkg.GoFiles[0])-len(filepath.Base(pkg.GoFiles[0]))], "reset.gen.go")
		if err := os.WriteFile(outPath, code, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", outPath, err)
		}
		fmt.Printf("generated %s\n", outPath)
	}
	return nil
}

func parseDirRecursive(fset *token.FileSet, root string) (map[string]*packages.Package, error) {
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedSyntax,
		Fset: fset,
	}
	pkgs, err := packages.Load(cfg, "./...")
	if err != nil {
		return nil, err
	}
	result := make(map[string]*packages.Package)
	for _, pkg := range pkgs {
		if len(pkg.Errors) > 0 {
			continue
		}
		if strings.HasPrefix(pkg.PkgPath, "cmd") {
			continue
		}
		result[pkg.PkgPath] = pkg
	}
	return result, nil
}

type structInfo struct {
	name   string
	fields []*ast.Field
}

func findMarkedStructs(pkg *packages.Package) []structInfo {
	var result []structInfo

	for _, f := range pkg.Syntax {
		for _, decl := range f.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}

			for _, spec := range gd.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}

				if !hasMarker(gd.Doc) && !hasMarker(ts.Doc) {
					continue
				}

				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					continue
				}

				result = append(result, structInfo{
					name:   ts.Name.Name,
					fields: st.Fields.List,
				})
			}
		}
	}

	return result
}

func hasMarker(doc *ast.CommentGroup) bool {
	if doc == nil {
		return false
	}
	for _, c := range doc.List {
		txt := strings.TrimSpace(c.Text)
		if txt == marker || strings.HasPrefix(txt, marker+" ") || strings.HasPrefix(txt, marker+"\t") {
			return true
		}
	}
	return false
}

func generateFile(pkgName string, structs []structInfo) ([]byte, error) {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by cmd/reset; DO NOT EDIT.\n")
	buf.WriteString(fmt.Sprintf("package %s\n", pkgName))

	for _, s := range structs {
		buf.WriteString(generateResetMethod(s))
	}

	out, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format: %w\nsource:\n%s", err, buf.String())
	}
	return out, nil
}

func generateResetMethod(s structInfo) string {
	var buf bytes.Buffer

	receiver := strings.ToLower(s.name[:1])

	buf.WriteString(fmt.Sprintf("func (%s *%s) Reset() {\n", receiver, s.name))
	buf.WriteString(fmt.Sprintf("\tif %s == nil {\n\t\treturn\n\t}\n\n", receiver))

	for _, field := range s.fields {
		for _, name := range field.Names {
			lines := generateFieldReset(receiver, name.Name, field.Type)
			for _, line := range lines {
				buf.WriteString("\t" + line + "\n")
			}
		}
	}

	buf.WriteString("}\n")
	return buf.String()
}

func generateFieldReset(receiver, fieldName string, expr ast.Expr) []string {
	access := fmt.Sprintf("%s.%s", receiver, fieldName)

	switch t := expr.(type) {
	case *ast.Ident:
		return []string{fmt.Sprintf("%s = %s", access, zeroValue(t.Name))}

	case *ast.StarExpr:
		var innerType string
		if ident, ok := t.X.(*ast.Ident); ok {
			innerType = ident.Name
		} else if sel, ok := t.X.(*ast.SelectorExpr); ok {
			innerType = selectorString(sel)
		}

		switch innerType {
		case "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64",
			"float32", "float64",
			"string", "bool", "byte", "rune":
			return []string{
				fmt.Sprintf("if %s != nil {", access),
				fmt.Sprintf("*%s = %s", access, zeroValue(innerType)),
				"}",
			}
		default:
			return []string{
				fmt.Sprintf("if %s != nil {", access),
				fmt.Sprintf("if resetter, ok := %s.(interface{ Reset() }); ok {", access),
				"resetter.Reset()",
				"} else {",
				fmt.Sprintf("*%s = %s{}", access, innerType),
				"}",
				"}",
			}
		}

	case *ast.ArrayType:
		if t.Elt == nil {
			return []string{fmt.Sprintf("%s = %s[:0]", access, access)}
		}
		return []string{fmt.Sprintf("%s = %s[:0]", access, access)}

	case *ast.MapType:
		return []string{fmt.Sprintf("clear(%s)", access)}

	case *ast.SelectorExpr:
		typeName := selectorString(t)
		return []string{
			fmt.Sprintf("if resetter, ok := %s.(interface{ Reset() }); ok {", access),
			"resetter.Reset()",
			"} else {",
			fmt.Sprintf("%s = %s{}", access, typeName),
			"}",
		}

	case *ast.StructType:
		return []string{
			fmt.Sprintf("%s.Reset()", access),
		}

	default:
		return []string{fmt.Sprintf("%s = %s", access, zeroValueForExpr(expr))}
	}
}

func selectorString(sel *ast.SelectorExpr) string {
	if ident, ok := sel.X.(*ast.Ident); ok {
		return ident.Name + "." + sel.Sel.Name
	}
	return sel.Sel.Name
}

func zeroValue(typeName string) string {
	switch typeName {
	case "bool":
		return "false"
	case "string":
		return `""`
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"float32", "float64",
		"byte", "rune",
		"complex64", "complex128":
		return "0"
	default:
		return typeName + "{}"
	}
}

func zeroValueForExpr(expr ast.Expr) string {
	if ident, ok := expr.(*ast.Ident); ok {
		return zeroValue(ident.Name)
	}
	if sel, ok := expr.(*ast.SelectorExpr); ok {
		return selectorString(sel) + "{}"
	}
	return "nil"
}
